# Generated by Django 2.1.4 on 2018-12-20 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data do evento')),
                ('hora', models.TimeField()),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'tarefas agendadas',
                'verbose_name': 'tafera agendada',
            },
        ),
        migrations.CreateModel(
            name='LocalEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='itemagenda',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgendaAdmin.LocalEvento'),
        ),
        migrations.AddField(
            model_name='itemagenda',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
